version: 2
jobs:
  build:
    working_directory: ~/notePad
    docker:
      - image: circleci/android:api-26-node8-alpha
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Accept Licenses
          command: echo y | sdkmanager --licenses && sdkmanager --update
      #- run:
      #    name: Install AWS CLI
      #    command: sudo apt-get -y -qq install awscli
      #- run: 
      #    name: Download Dependencies
      #    command: ./gradlew androidDependencies -PdisablePreDex
      #- run:
      #    name: Create apks
      #    command: ./gradlew clean assambleDebug assambleAndroidTest
      - persist_to_workspace:
          root: ~/notePad
          paths:
            - NotePad/
  
  upload_to_AWS:
    working_directory: ~/notePad
    docker:
      - image: circleci/python:3.6.1
    steps:
      - attach_workspace:
          at: ~/tmp/notePad/
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - run: pip install --upgrade pip
      - run:
          command: sudo pip install boto3
      - run:
          command: ls
      - run:
          command: cd tmp
      - run:
          command: ls
          #command: os.chmod(DeviceFarm.py, 0o444) 
          #command: python ./tmp/notePad/DeviceFarm.py
      
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              #We want to run this on every tag
              only: /.*/
      - upload_to_AWS:
          requires:
            - build
          filters:
            tags:
              #We want to run this on every tag
              only: /.*/
