version: 2
jobs:
  build:
    working_directory: ~/NotePad
    docker:
      - image: circleci/android:api-26-node8-alpha
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Accept Licenses
          command: echo y | sdkmanager --licenses && sdkmanager --update
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      #- run: 
      #    name: Download Dependencies
      #    command: ./gradlew androidDependencies -PdisablePreDex
      #- run:
      #    name: Create apks
      #    command: ./gradlew clean assambleDebug assambleAndroidTest
  
  upload_to_AWS:
    steps:
      - run: pip install PIL --allow-external PIL --allow-unverified PIL
      
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              #We want to run this on every tag
              only: /.*/
      - upload_to_AWS:
          filters:
            tags:
              #We want to run this on every tag
              only: /.*/
