version: 2
jobs:
  build:
    working_directory: ~/flipp
    docker:
      - image: circleci/android:api-26-node8-alpha
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Accept Licenses
          command: echo y | sdkmanager --licenses && sdkmanager --update
      #- run:
      #    name: Install AWS CLI
      #    command: sudo apt-get -y -qq install awscli
      #- run: 
      #    name: Download Dependencies
      #    command: ./gradlew androidDependencies -PdisablePreDex
      #- run:
      #    name: Create apks
      - persist_to_workspace:
          root: /home/circleci/flipp
          paths:
            - NotePad/app/build/outputs/apk/
            - .circleci/
  
  upload_to_AWS:
    working_directory: ~/flipp
    docker:
      - image: circleci/python:2-browsers
    steps:
      - attach_workspace:
          at: ~/flipp
      - run:
          name: Upgrade PIP
          command: sudo pip install --upgrade pip
      - run:
          name: Install AWS CLI
          command: sudo pip install awscli --upgrade
      - run:
          command: sudo pip install --upgrade pprintpp
      - run: 
          command: sudo pip install boto3 --upgrade
      - run: 
          command: sudo pip install requests --upgrade
      - run:
          command: cd NotePad/app/build/outputs/apk && ls
      - run:
          command: |
            aws configure list
            export AWS_ACCESS_KEY_ID=$AWS_KEY	
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRETE_KEY
            #aws configure set aws_access_key_id $AWS_KEY
            #aws configure set aws_secret_access_key $AWS_SECRETE_KEY
            aws configure list
            ls
            ls
            cd .circleci && python DeviceFarm.py
            
  firebase_upload:
    working_directory: ~/flipp
    docker:
      - image: circleci/android:api-26-node8-alpha
    steps:
      - attach_workspace:
          at: ~/flipp
      - run:
          name: Install crcmod
          command: sudo pip install -U crcmod
      - run:
          command: |         
            echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/client-secret.json
            sudo gcloud config set project flipp-automation-suites
            sudo apt-get update
            sudo apt-get install google-cloud-sdk
            sudo gcloud auth login FireFlippService --key-file ${HOME}/client-secret.json
 
      - run:
          name: Running Tests in Firebase
          command: |
            echo "Test to Firebase" | sudo /opt/google-cloud-sdk/bin/gcloud beta firebase test android \
            run --type instrumentation \
            --app Flipp/build/outputs/apk/debug/Flipp-debug.apk \
            --test Flipp/build/outputs/apk/androidTest/debug/Flipp-debug-androidTest.apk \
            --device model=Nexus6,version=21,locale=en \
            --results-bucket cloud-test-flipp-automation-suites
      
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              #We want to run this on every tag
              only: /.*/
      - upload_to_AWS:
          requires:
            - build
          filters:
            tags:
              #We want to run this on every tag
              only: /.*/
      - firebase_upload:
          requires:
            - build
          filters:
            tags:
              only: /.*/
